spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8089/user-service/**
          predicates:
            - Path=/user-service/**
        - id: main_service
          uri: http://localhost:8089/main/**
          predicates:
            - Path=/main/**
        - id: first_service
          uri: lb://first-service/first-service/**
          predicates:
            - Path=/first-service/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka

