spring:
  messages:
    basename: messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mh?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
multipart:
  max-file-size: 10MB
  max-request-size: 10MB
  file-size-threshold: 0


mh:
  jwt:
    secret: mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004
    access-token-expiration: 86400000
    refresh-token-expiration: 2592000000


kakao:
  client:
    id: cf2d93f813f588cb0616341a7a287487
    secret: Hr7gAtRILsnFEZB6IWxt3SRdnJXlOi0F